- name: Perform Server Checks
  hosts: master
  gather_facts: yes
  tasks:
    - name: Ping the Server
      ping:
      register: ping_status

    - name: Debug Ping Status
      debug:
        var: ping_status

    - name: Check Hardware Health
      command: lshw
      register: hardware_health_output

    - name: Debug Hardware Health Output
      debug:
        var: hardware_health_output

    - name: Get OS Version and Updates
      command: cat /etc/redhat-release
      register: os_version

    - name: Debug OS Version
      debug:
        var: os_version

    - name: Check Filesystem and Disk Space
      command: df -Th
      register: filesystem_space 

    - name: Debug Filesystem Space
      debug:
        var: filesystem_space
